name: Build

on:
  pull_request:
  push:
  
env:
  INVALID_TITLE_PULL: "Pull request title should be started with 'TEST-XXXX'"
  INVALID_COMMIT_MESSAGE: "Commit message should be started with one of the following options: 'TEST-XXXX feat(file-name): Message', 'TEST-XXXX fix(file-name): Message', 'TEST-XXXX test(file-name): Message'"
  
jobs:
  validation-pull:
    runs-on: ubuntu-latest
    steps:
      - name: Check title pull
        if: ${{ !startsWith( github.event.pull_request.title, 'TEST-' ) && ( github.event.pull_request.title != null ) }}
        run: |
          echo ${{ github.event.pull_request.title }}
          echo ${{ env.INVALID_TITLE_MESSAGE }} && exit 1

  validation-commits:
    runs-on: ubuntu-latest
    steps:
      - name: Check commits message
        uses: gsactions/commit-message-checker@v1
        with:
          pattern: '^TEST-[0-9]{3,5}[ ](fix|test|feat)\([a-zA-Z0-9-_. ]{1,64}\):'
          flags: 'gm'
          checkAllCommitMessages: 'true'
          error: ${{ env.INVALID_COMMIT_MESSAGE }}

  build:
    needs: [validation-pull, validation-commits]
    runs-on: ubuntu-latest
    steps:
      - name: Start Build
        run: echo ${{ env.NAME }}
      - name: Finish Build
        run: echo "Hello ${{ env.NAME }}"
