name: Build

on:
  pull_request:
  push:
    branches: 
      - main

env:
  NAME: 'Test Testov'
  
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Step one
      run: echo "Hello ${{ env.NAME }}"
