name: Build

on:
  pull_request:
  push:

env:
  INVALID_TITLE_MESSAGE: "Pull request title should be started with 'TEST-XXX'"


  
jobs:
  validation-commit:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        commits: github.event.commits
    steps:
      - name: Invalid commit message ${{matrix.commits.message}}
        if: ${{ !startsWith( matrix.commits.message, 'TEST-' ) && ( matrix.commits.message != null ) }}
        run: |
          echo ${{ matrix.commits.message }}
          echo ${{ env.INVALID_TITLE_MESSAGE }} && exit 1

  build:
    needs: validation-commit
    runs-on: ubuntu-latest
    steps:
      - name: Start Build
        run: echo ${{ matrix.commits.message }}
      - name: Finish Build
        run: echo "Hello ${{ env.NAME }}"
