name: Build

on:
  pull_request:
  push:

env:
  NAME: 'Test Testov'
  INVALID_TITLE_MESSAGE: "Pull request title should be started with 'TEST-XXX'"
  
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Start Build
        run: echo "Hello ${{ github.event.commit_comment }}"
      - name: Invalid title
        if: ${{ !startsWith( github.event.commit_comment, 'TEST-' ) && ( github.event.commit_comment.comment != null ) }}
        run: |
          echo ${{ github.event.commit_comment.comment }}
          echo ${{ env.INVALID_TITLE_MESSAGE }} && exit 1
      - name: Finish Build
        run: echo "Hello ${{ env.NAME }}"
