name: Build

on:
  pull_request:
  push:
    branches: 
      - main

env:
  TITLE_TEST: 'Hello from builder'
  
jobs:
  # This workflow contains a single job called "greet"
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Step #1
      run: echo "Hello ${{ env.TITLE_TEST }}"
