name: Build

on:
  pull_request:
  push:

env:
  NAME: 'Test Testov'
  INVALID_TITLE_MESSAGE: "Pull request title should be started with 'TEST-XXX'"
  
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Start Build
      run: echo "Hello ${{ env.NAME }}"
    - name: Finish Build
      run: echo "Hello ${{ env.NAME }}"
