name: Build

on:
  pull_request:
  push:

env:
  INVALID_TITLE_PULL: "Pull request title should be started with 'TEST-XXXX'"
  INVALID_COMMIT_MESSAGE: "Commit message should be started with one of the following options: 'feat/TEST-XXX', 'fix/TEST-XXX', 'test/TEST-XXX'"
  
jobs:
  validation-pull:
    runs-on: ubuntu-latest
    steps:
      - name: Check title pull
        if: ${{ !startsWith( github.event.pull_request.title, 'TEST-' ) && ( github.event.pull_request.title != null ) }}
        run: |
          echo ${{ github.event.pull_request.title }}
          echo ${{ env.INVALID_TITLE_MESSAGE }} && exit 1

  validation-commit:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        commits: ${{github.event.commits}}
        patterns: ['feat/TEST-', 'fix/TEST-']
    steps:
      - name: Check commit message ${{matrix.commits.message}}
        if: ${{ !startsWith( matrix.commits.message, matrix.patterns ) && ( matrix.commits.message != null ) }}
        run: |
          echo ${{ matrix.commits.message }}
          echo ${{ env.INVALID_COMMIT_MESSAGE }} && exit 1

  build:
    needs: [validation-pull, validation-commit]
    runs-on: ubuntu-latest
    steps:
      - name: Start Build
        run: echo ${{ matrix.commits.message }}
      - name: Finish Build
        run: echo "Hello ${{ env.NAME }}"
